import React, { useEffect, useState } from 'react';
import API from '../../services/api';
import FacultyNavbar from '../../components/common/FacultyNavbar';

const FacultyAttendance = () => {
	const [students, setStudents] = useState([]);
	const [subjects, setSubjects] = useState([]);
	const [form, setForm] = useState({ student: '', subject: '', date: new Date().toISOString().slice(0, 10), status: 'present' });
	const [message, setMessage] = useState('');
	useEffect(() => { Promise.all([API.get('/students?limit=100'), API.get('/subjects')]).then(([studentsRes, subjectsRes]) => { setStudents(studentsRes.data?.data || []); setSubjects(subjectsRes.data?.data || []); }).catch(() => setMessage('Unable to load students or subjects.')); }, []);
	const submit = async (event) => { event.preventDefault(); setMessage(''); try { await API.post('/attendance', form); setMessage('Attendance recorded successfully.'); } catch (error) { setMessage(error.response?.data?.message || 'Attendance could not be recorded.'); } };
	return <div className="min-h-screen bg-slate-50 dark:bg-slate-950"><FacultyNavbar /><main className="mx-auto max-w-5xl space-y-6 p-4 sm:p-8"><header><p className="text-xs font-semibold uppercase tracking-[0.2em] text-violet-600">Academic operations</p><h1 className="mt-2 text-3xl font-black">Record attendance</h1><p className="mt-1 text-sm text-slate-500">Attendance is saved to the server and can be updated through the attendance API.</p></header><form onSubmit={submit} className="grid gap-4 rounded-xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900 sm:grid-cols-2"><label className="text-sm font-semibold">Student<select required value={form.student} onChange={(e) => setForm({ ...form, student: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 bg-transparent p-2.5 font-normal dark:border-slate-700"><option value="">Select student</option>{students.map((student) => <option key={student._id} value={student._id}>{student.studentId} - {student.userId?.name || 'Unnamed student'}</option>)}</select></label><label className="text-sm font-semibold">Subject<select required value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 bg-transparent p-2.5 font-normal dark:border-slate-700"><option value="">Select subject</option>{subjects.map((subject) => <option key={subject._id} value={subject._id}>{subject.code} - {subject.name}</option>)}</select></label><label className="text-sm font-semibold">Date<input required type="date" value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 bg-transparent p-2.5 font-normal dark:border-slate-700" /></label><label className="text-sm font-semibold">Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })} className="mt-1 w-full rounded-lg border border-slate-300 bg-transparent p-2.5 font-normal dark:border-slate-700"><option value="present">Present</option><option value="absent">Absent</option><option value="late">Late</option></select></label><div className="sm:col-span-2"><button className="rounded-lg bg-violet-700 px-5 py-2.5 text-sm font-bold text-white hover:bg-violet-800">Save attendance</button>{message && <p className="mt-3 text-sm text-slate-600 dark:text-slate-300">{message}</p>}</div></form></main></div>;
};

export default FacultyAttendance;