import React, { useEffect, useState } from 'react';
import { BookOpen, CircleDollarSign, FileCheck, Trash2, Upload, UserPlus } from 'lucide-react';
import API, { API_ORIGIN } from '../../services/api';
import FacultyNavbar from '../../components/common/FacultyNavbar';

const semesters = [1, 2, 3, 4, 5, 6];
const emptyStudent = { name: '', email: '', password: '', phone: '', studentId: '', department: '', course: '', semester: '', section: '', dateOfBirth: '', address: '', guardianName: '', guardianPhone: '' };
const emptyFee = { student: '', academicYear: '', semester: '', feeType: '', amount: '', dueDate: '', status: 'pending' };
const emptyResult = { student: '', subject: '', examination: '', marks: '', maxMarks: 100, remarks: '' };

export default function FacultyOperations() {
  const [students, setStudents] = useState([]); const [departments, setDepartments] = useState([]); const [courses, setCourses] = useState([]); const [subjects, setSubjects] = useState([]); const [examinations, setExaminations] = useState([]); const [materials, setMaterials] = useState([]);
  const [student, setStudent] = useState(emptyStudent); const [fee, setFee] = useState(emptyFee); const [result, setResult] = useState(emptyResult); const [material, setMaterial] = useState({ title: '', course: '', subject: '', semester: '', file: null }); const [message, setMessage] = useState('');

  const load = async () => {
    const responses = await Promise.all([API.get('/students?limit=500'), API.get('/departments?status=active'), API.get('/courses?status=active'), API.get('/subjects'), API.get('/examinations?limit=500'), API.get('/materials')]);
    setStudents(responses[0].data?.data || []); setDepartments(responses[1].data?.data || []); setCourses(responses[2].data?.data || []); setSubjects(responses[3].data?.data || []); setExaminations(responses[4].data?.data || []); setMaterials(responses[5].data?.data || []);
  };
  useEffect(() => { load().catch((error) => setMessage(error.response?.data?.message || 'Unable to load operations data.')); }, []);
  const errorMessage = (error, fallback) => error.response?.data?.message || fallback;
  const createStudent = async (event) => { event.preventDefault(); try { await API.post('/students', { ...student, semester: Number(student.semester) }); setStudent(emptyStudent); await load(); setMessage('Student saved and assigned to you.'); } catch (error) { setMessage(errorMessage(error, 'The student could not be created.')); } };
  const createFee = async (event) => { event.preventDefault(); try { await API.post('/fees', { ...fee, semester: Number(fee.semester), amount: Number(fee.amount), paidAmount: fee.status === 'paid' ? Number(fee.amount) : 0 }); setFee(emptyFee); setMessage('Fee record saved successfully.'); } catch (error) { setMessage(errorMessage(error, 'The fee record could not be created.')); } };
  const createResult = async (event) => { event.preventDefault(); try { await API.post('/results', { ...result, marks: Number(result.marks), maxMarks: Number(result.maxMarks) }); setResult(emptyResult); setMessage('Marks saved. Grade and CGPA inputs updated successfully.'); } catch (error) { setMessage(errorMessage(error, 'The marks could not be saved.')); } };
  const uploadMaterial = async (event) => { event.preventDefault(); if (!material.file) return setMessage('Choose a material file first.'); const body = new FormData(); Object.entries(material).forEach(([key, value]) => value !== null && body.append(key, value)); try { await API.post('/materials', body, { headers: { 'Content-Type': 'multipart/form-data' } }); setMaterial({ title: '', course: '', subject: '', semester: '', file: null }); event.target.reset(); await load(); setMessage('Material uploaded successfully.'); } catch (error) { setMessage(errorMessage(error, 'Material upload failed.')); } };
  const deleteMaterial = async (id) => { if (!window.confirm('Delete this material?')) return; await API.delete(`/materials/${id}`); await load(); };
  const filteredCourses = courses.filter((item) => !student.department || String(item.department?._id || item.department) === String(student.department));

  const inputClass = 'rounded-lg border border-slate-300 bg-transparent p-2.5 text-sm dark:border-slate-700';
  const studentFields = [['name', 'Full name', 'text'], ['email', 'Email', 'email'], ['password', 'Temporary password', 'password'], ['phone', 'Phone', 'tel'], ['studentId', 'Roll number', 'text'], ['section', 'Section', 'text'], ['dateOfBirth', 'Date of birth', 'date'], ['guardianName', 'Guardian name', 'text'], ['guardianPhone', 'Guardian phone', 'tel']];

  return <div className="min-h-screen bg-slate-50 dark:bg-slate-950"><FacultyNavbar /><main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-8"><header><p className="text-xs font-semibold uppercase tracking-[0.2em] text-violet-600">Faculty operations</p><h1 className="mt-2 text-3xl font-black">Academic administration</h1><p className="mt-1 text-sm text-slate-500">Manage students, marks, semester fees, and learning materials.</p></header>{message && <p className="rounded-lg bg-violet-50 p-3 text-sm font-semibold text-violet-800 dark:bg-violet-950/30 dark:text-violet-200">{message}</p>}
    <div className="grid gap-6 lg:grid-cols-2">
      <form onSubmit={createStudent} className="space-y-4 rounded-xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="flex items-center gap-2 text-lg font-bold"><UserPlus className="h-5 w-5 text-violet-600" /> Add student</h2><div className="grid gap-3 sm:grid-cols-2">{studentFields.map(([key, label, type]) => <input key={key} required={['name', 'email', 'password', 'studentId', 'section'].includes(key)} type={type} placeholder={label} value={student[key]} onChange={(event) => setStudent({ ...student, [key]: event.target.value })} className={inputClass} />)}</div><textarea placeholder="Address" value={student.address} onChange={(event) => setStudent({ ...student, address: event.target.value })} className={`${inputClass} min-h-20 w-full`} /><select required value={student.department} onChange={(event) => setStudent({ ...student, department: event.target.value, course: '' })} className={inputClass}><option value="">Select department</option>{departments.map((item) => <option key={item._id} value={item._id}>{item.code} - {item.name}</option>)}</select><div className="grid gap-3 sm:grid-cols-2"><select required value={student.course} onChange={(event) => setStudent({ ...student, course: event.target.value })} className={inputClass}><option value="">Select course</option>{filteredCourses.map((item) => <option key={item._id} value={item._id}>{item.code} - {item.name}</option>)}</select><select required value={student.semester} onChange={(event) => setStudent({ ...student, semester: event.target.value })} className={inputClass}><option value="">Select semester</option>{semesters.map((item) => <option key={item} value={item}>{item}</option>)}</select></div><button className="rounded-lg bg-violet-700 px-4 py-2 text-sm font-bold text-white">Create student</button></form>
      <form onSubmit={createResult} className="space-y-4 rounded-xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="flex items-center gap-2 text-lg font-bold"><FileCheck className="h-5 w-5 text-indigo-600" /> Enter marks and CGPA inputs</h2><select required value={result.student} onChange={(event) => setResult({ ...result, student: event.target.value })} className={`${inputClass} w-full`}><option value="">Select student</option>{students.map((item) => <option key={item._id} value={item._id}>{item.studentId} - {item.userId?.name}</option>)}</select><select required value={result.subject} onChange={(event) => setResult({ ...result, subject: event.target.value })} className={`${inputClass} w-full`}><option value="">Select subject</option>{subjects.map((item) => <option key={item._id} value={item._id}>{item.code} - {item.name}</option>)}</select><select required value={result.examination} onChange={(event) => setResult({ ...result, examination: event.target.value })} className={`${inputClass} w-full`}><option value="">Select examination</option>{examinations.map((item) => <option key={item._id} value={item._id}>{item.name} - {item.subject?.code || ''}</option>)}</select><div className="grid gap-3 sm:grid-cols-2"><input required min="0" max={result.maxMarks} type="number" placeholder="Marks obtained" value={result.marks} onChange={(event) => setResult({ ...result, marks: event.target.value })} className={inputClass} /><input required min="1" type="number" placeholder="Maximum marks" value={result.maxMarks} onChange={(event) => setResult({ ...result, maxMarks: event.target.value })} className={inputClass} /></div><input placeholder="Remarks (optional)" value={result.remarks} onChange={(event) => setResult({ ...result, remarks: event.target.value })} className={`${inputClass} w-full`} /><button className="rounded-lg bg-indigo-700 px-4 py-2 text-sm font-bold text-white">Save marks and calculate grade</button></form>
      <form onSubmit={createFee} className="space-y-4 rounded-xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="flex items-center gap-2 text-lg font-bold"><CircleDollarSign className="h-5 w-5 text-emerald-600" /> Add semester fee</h2><select required value={fee.student} onChange={(event) => setFee({ ...fee, student: event.target.value })} className={`${inputClass} w-full`}><option value="">Select student</option>{students.map((item) => <option key={item._id} value={item._id}>{item.studentId} - {item.userId?.name}</option>)}</select><input required placeholder="Academic year" value={fee.academicYear} onChange={(event) => setFee({ ...fee, academicYear: event.target.value })} className={`${inputClass} w-full`} /><div className="grid gap-3 sm:grid-cols-2"><select required value={fee.feeType} onChange={(event) => setFee({ ...fee, feeType: event.target.value })} className={inputClass}><option value="">Select fee type</option><option value="examination">Examination</option><option value="lab">Lab</option><option value="tuition">Tuition</option></select><input required type="number" placeholder="Amount" value={fee.amount} onChange={(event) => setFee({ ...fee, amount: event.target.value })} className={inputClass} /><input required type="date" value={fee.dueDate} onChange={(event) => setFee({ ...fee, dueDate: event.target.value })} className={inputClass} /><select required value={fee.semester} onChange={(event) => setFee({ ...fee, semester: event.target.value })} className={inputClass}><option value="">Select semester</option>{semesters.map((item) => <option key={item} value={item}>{item}</option>)}</select></div><select required value={fee.status} onChange={(event) => setFee({ ...fee, status: event.target.value })} className={`${inputClass} w-full`}><option value="pending">Not paid</option><option value="paid">Paid</option></select><button className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-bold text-white">Create fee record</button></form>
    </div>
    <form onSubmit={uploadMaterial} className="space-y-4 rounded-xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="flex items-center gap-2 text-lg font-bold"><BookOpen className="h-5 w-5 text-cyan-600" /> Upload learning material</h2><div className="grid gap-3 sm:grid-cols-3"><input required placeholder="Material title" value={material.title} onChange={(event) => setMaterial({ ...material, title: event.target.value })} className={inputClass} /><select required value={material.course} onChange={(event) => setMaterial({ ...material, course: event.target.value, subject: '' })} className={inputClass}><option value="">Course</option>{courses.map((item) => <option key={item._id} value={item._id}>{item.code}</option>)}</select><select required value={material.semester} onChange={(event) => setMaterial({ ...material, semester: event.target.value, subject: '' })} className={inputClass}><option value="">Semester</option>{semesters.map((item) => <option key={item} value={item}>{item}</option>)}</select></div><div className="flex flex-wrap gap-3"><label className="flex min-w-[240px] flex-1 flex-col gap-1 text-xs font-semibold text-slate-600 dark:text-slate-300">All existing subjects<select required value={material.subject} onChange={(event) => setMaterial({ ...material, subject: event.target.value })} className={inputClass}><option value="">{subjects.length ? 'Select a subject' : 'No subjects available'}</option>{subjects.map((item) => <option key={item._id} value={item._id}>{item.code} - {item.name}</option>)}</select></label><input type="file" required onChange={(event) => setMaterial({ ...material, file: event.target.files?.[0] || null })} className={inputClass} /><button className="inline-flex items-center gap-2 rounded-lg bg-cyan-700 px-4 py-2 text-sm font-bold text-white"><Upload className="h-4 w-4" /> Upload</button></div></form>
    <section className="rounded-xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-bold">Published materials</h2>{materials.length ? materials.map((item) => <div key={item._id} className="flex items-center justify-between border-b py-3 text-sm"><a href={`${API_ORIGIN}${item.fileUrl}`} target="_blank" rel="noreferrer" className="font-semibold text-cyan-700">{item.title}</a><button onClick={() => deleteMaterial(item._id)} className="text-rose-600" title="Delete"><Trash2 className="h-4 w-4" /></button></div>) : <p className="py-4 text-sm text-slate-500">No materials uploaded yet.</p>}</section>
  </main></div>;
}
